### ISSUE TITLE
As a user, I would like to be able to see all products in one view so that I can shop all products.

### ISSUE THREAD

**Issue by KatieGuest** [ghpurpleparrots/graceshopper#4]
- [] route for all products (#13)
- [] products model (#14)
- [] products reducer (#15)
- [] products react component (#16)
- [] link from homepage (#17)
